"""candidate table

Revision ID: 16b8db0c0544
Revises: f3189750b0fb
Create Date: 2026-03-24 10:16:57.396934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b8db0c0544'
down_revision: Union[str, Sequence[str], None] = 'f3189750b0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=255), server_default=sa.text("'created'::character varying"), nullable=False),
    sa.Column('user_created', sa.Uuid(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_updated', sa.Uuid(), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('profile_info', sa.JSON(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('progress', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('custom_password_set', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('personas', sa.String(length=255), nullable=True),
    sa.Column('roles', sa.String(length=255), nullable=True),
    sa.Column('last_sent_email', sa.DateTime(), nullable=True),
    sa.Column('vacancy_match', sa.String(length=255), nullable=True),
    sa.Column('privacy_settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate')
    # ### end Alembic commands ###
